-- Created on 2016/4/3 by XIE 
declare 
  -- Local variables here
  i integer;
begin
 EXECUTE IMMEDIATE Q'{CREATE OR REPLACE PROCEDURE DICT_SYNCHRONIZE_CREATE_TABLE(TABLENAME VARCHAR2,ORIGINAL_TABLENAME VARCHAR2) AUTHID CURRENT_USER as
  V_COUNT NUMBER;
  V_SQL VARCHAR2(200);
BEGIN
  SELECT COUNT(1) INTO V_COUNT FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE' AND OBJECT_NAME=TABLENAME;
  IF(V_COUNT = 1) THEN
      V_SQL := 'DROP TABLE '||TABLENAME;
      EXECUTE IMMEDIATE V_SQL;
  END IF;
  V_SQL := 'CREATE TABLE '||TABLENAME||' AS SELECT * FROM '||ORIGINAL_TABLENAME||' WHERE ROWNUM < 1';
  EXECUTE IMMEDIATE V_SQL;
  END DICT_SYNCHRONIZE_CREATE_TABLE;}';

  EXECUTE IMMEDIATE Q'{
  CREATE OR REPLACE PROCEDURE DICT_SYNCHRONIZE_DATA(TABLENAME          VARCHAR2,
                                                  ORIGINAL_TABLENAME VARCHAR2) AUTHID CURRENT_USER as
  V_PRIMARY_COL   VARCHAR2(20000);
  V_NOPRIMARY_COL VARCHAR2(20000);
  V_COLUMN_NAME   VARCHAR2(20000);
  V_CONDITION     VARCHAR2(30000);
  V_INSERT_SQL    VARCHAR2(32000);
  V_UPDATE_SQL    VARCHAR2(32000);
  V_DELETE_SQL    VARCHAR2(32000);
  V_DROP_SQL      VARCHAR2(1000);
  V_COUNT         NUMBER;
  V_TEST          VARCHAR2(100);
  V_CHECK         VARCHAR2(10000);
begin
  --如果当前临时表没有数据，则退出存储过程
  V_TEST := 'SELECT COUNT(1) FROM ' || TABLENAME;
  EXECUTE IMMEDIATE V_TEST
    INTO V_COUNT;
  IF V_COUNT > 0 AND ORIGINAL_TABLENAME != 'P#FORMULA_T_FORMULADEF' THEN
    --T0是原表，T1是目标临时表
    --查原表的主键名字,并且要排除STATUS，否则按照主键查询时，如果
    --临时表STATUS=2，即被逻辑删了，而原表为STATUS=1，在用主键判断时，
    --就会直接插入一条新的数据，而不是将原表的数据更新为逻辑删状态
    for V_COLUMN_NAME in (SELECT T1.COLUMN_NAME
                            FROM USER_CONS_COLUMNS T1, USER_CONSTRAINTS T2
                           WHERE T1.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
                             AND T2.CONSTRAINT_TYPE = 'P'
                             AND T1.TABLE_NAME = ORIGINAL_TABLENAME
                             AND T1.COLUMN_NAME <> 'STATUS') loop
      V_PRIMARY_COL := V_PRIMARY_COL || '' || v_COLUMN_NAME.Column_Name ||',';
      V_CONDITION   := V_CONDITION || ' AND ' || ORIGINAL_TABLENAME ||'.'||
                       v_COLUMN_NAME.Column_Name || ' = '|| TABLENAME || '.' ||
                       v_COLUMN_NAME.Column_Name;
    end loop;
    --截取最后一个,字符
    SELECT rtrim(V_PRIMARY_COL, ',') INTO V_PRIMARY_COL FROM DUAL;
    --将临时表重复数据删除
    V_CHECK := '
      BEGIN
        LOOP
          DELETE FROM '||TABLENAME||' WHERE ROWID in (SELECT MAX(ROWID) FROM '||TABLENAME||' GROUP BY ('||V_PRIMARY_COL||') HAVING COUNT(*) > 1);
          EXIT WHEN SQL%ROWCOUNT < 1;
        END LOOP;
      END;';
    EXECUTE IMMEDIATE V_CHECK;

    --截取前4个字符，‘ AND’
    SELECT substr(V_CONDITION, 5) INTO V_CONDITION FROM DUAL;
    V_INSERT_SQL := 'INSERT INTO ' || ORIGINAL_TABLENAME ||
                    ' SELECT * FROM ' || TABLENAME ||
                    ' WHERE NOT EXISTS(SELECT 1 FROM '||ORIGINAL_TABLENAME||' WHERE ' ||
                    V_CONDITION || ')';

    for V_COLUMN_NAME in (SELECT COLUMN_NAME
                            FROM USER_TAB_COLS
                           WHERE TABLE_NAME = ORIGINAL_TABLENAME
                             AND COLUMN_NAME NOT IN (V_PRIMARY_COL)) loop
      V_NOPRIMARY_COL := V_NOPRIMARY_COL || '' ||
                         V_COLUMN_NAME.COLUMN_NAME || ',';
    end loop;
    SELECT replace(rtrim(V_NOPRIMARY_COL, ','), ', ')
      INTO V_NOPRIMARY_COL
      FROM DUAL;
    V_UPDATE_SQL := 'UPDATE ' || ORIGINAL_TABLENAME || ' SET(' ||
                    V_NOPRIMARY_COL || ')=(SELECT ' || V_NOPRIMARY_COL ||
                    ' FROM ' || TABLENAME || ' WHERE ' || V_CONDITION ||
                    ') WHERE EXISTS(SELECT 1 FROM '||TABLENAME||' WHERE ' || V_CONDITION || ')';
    begin
      EXECUTE IMMEDIATE V_UPDATE_SQL;
     EXCEPTION
        WHEN OTHERS THEN
          RAISE_APPLICATION_ERROR(-20001,'更新表'||ORIGINAL_TABLENAME||'出现问题，有可能不存在主键或者存在错误的索引！请检查！更新语句为：'||V_UPDATE_SQL||','||SQLERRM);
     END;
     begin
      EXECUTE IMMEDIATE V_INSERT_SQL;
     EXCEPTION
        WHEN OTHERS THEN
          RAISE_APPLICATION_ERROR(-20001,'插入表'||ORIGINAL_TABLENAME||'出现问题，有可能不存在主键或者存在错误的索引！请检查！插入语句为：'||V_UPDATE_SQL||','||SQLERRM);
     END;
     END IF;
     end DICT_SYNCHRONIZE_DATA;}';

    EXECUTE IMMEDIATE Q'{
	    create or replace procedure DICT_SYNCHRONIZE_DEL_TABLE(TABLENAME VARCHAR2) AUTHID CURRENT_USER as
	    V_DROP_SQL      VARCHAR2(100);
	    begin
	      V_DROP_SQL := 'DROP TABLE ' || TABLENAME;
	        EXECUTE IMMEDIATE V_DROP_SQL;
	    end DICT_SYNCHRONIZE_DEL_TABLE;}';
	
		EXECUTE IMMEDIATE Q'{
			CREATE OR REPLACE PROCEDURE EXECPROCEDURE(SQLSTR CLOB) AS
	  BEGIN
	    IF SQLSTR IS NULL THEN
	      RETURN;
	    ELSE
	      EXECUTE IMMEDIATE SQLSTR;
	    END IF;
	  END;
	}';
	EXECUTE IMMEDIATE Q'{
		CREATE OR REPLACE PROCEDURE EXECPROCEDURE(SQLSTR CLOB) AUTHID CURRENT_USER as
	    BEGIN
	      IF SQLSTR IS NULL THEN
	        RETURN;
	      ELSE
	        EXECUTE IMMEDIATE SQLSTR;
	      END IF;
	    END;
	}';
end;